- name: Play 1
  hosts:
    - primary
  vars_files:
    - vars/vars.yml
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: debian
    # ansible_become_pass: toto
    file_name: "ici"
  tasks:
    - name: Create user
      ansible.builtin.user:
        name: "{{ item.login }}"
        password: $6$xyz$spwuoHJ2pJZNopKwAj/bo7SBT0tXyRDoe5pTGHFegBQv4a60jVLvIUy1UieEsnzo3RY0dn7hn92U9L28WV/DH1
        groups:
          - sudo
        shell: /bin/bash
      become: yes
      loop: "{{ users }}"

    - name: Remove Yassin user
      ansible.builtin.user:
        name: "yassin"
        state: absent
      become: yes
    
    - name: Remove Yassin home
      ansible.builtin.file:
        path: "/home/yassin"
        state: absent
      become: yes

    - name: "Set authorized key for user" 
      ansible.posix.authorized_key:
        user: "{{ item.login }}"
        state: absent
        key: "{{ item.key }}"
      become: yes
      loop: "{{ users }}"
    
    - name: "Set authorized key for user" 
      ansible.builtin.debug:
        msg: "{{ item.login }}"
      loop: "{{ users }}"